### ISSUE TITLE
[Feature] - Warn when classes aren't exported from cell?

### ISSUE THREAD

**Issue by goranmoomin** [3Nigma/nelu-kernelu#5]
Due to `let` & `const` variables not exposed outside of the defined cell, classes are also not exposed outside of the cell.

For example:
![image](https://user-images.githubusercontent.com/37990858/65209149-2af1fc80-dad2-11e9-8db7-b8b2976d3050.png)

I'm using a workaround by assigning a [class expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class) to a `var` variable, but it is unintuitive to do so.
![image](https://user-images.githubusercontent.com/37990858/65209191-51179c80-dad2-11e9-8a0b-70100857ec8c.png)

BTW, I think scoping `let` and `const` to each cell was a pretty good design choice; it lets evaluating cells multiple times much easier... so I'm not sure what's the best way to fix this.

I think warning that the class won't be exported when the cell only contains a class declaration (or more generally, contains only declarations that are scoped to a cell) might be more helpful?

**Comment by 3Nigma** [comment]
This one will be a bit more challenging to solve, but I believe we can tackle it if we parse the cell JSON with an [AST](https://www.npmjs.com/package/abstract-syntax-tree) and execute `class` declarations directly inside the JS VM Context. That way, they won't be scoped to a cell like `let` and `const`s are. 
Bringing in an AST will let us deal with more complex/niche JS behaviours in the future.

We'll follow-up on this today.

**Comment by goranmoomin** [comment]
@3Nigma Yeah, I’ve also thought about that; but I’m not sure if redefining same name classes are available.
(If they aren’t, executing class declarations directly might be more of a harm.)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 3Nigma** [comment]
Good point. The nice thing about ASTs is that you can work them backwards and morph the code into something logically equivalent. 
For instance, we can change behind the scenes (through AST manipulation) `class ABCD {}` into `ABCD = class {}` which allows us to do the following:
<img width="590" alt="Screenshot 2019-09-19 at 19 00 47" src="https://user-images.githubusercontent.com/210908/65261842-c5bdfb80-db11-11e9-8492-50433f3789da.png">
This might be a good workaround. We need to analyse this further.

**Comment by goranmoomin** [comment]
@3Nigma Yeah, but I'm not sure if that would be logical behavior considering the current behavior of `let` and `const` variables.
If this get's implemented, it should also rewrite all top-level `let` & `const` variables to `var` ones.
Maybe just transpiling all this to ES5 using babel might be a fine choice, since AFAIK `let` and `const` are both implemented with `var` (and what we're trying to do is basically what Babel does well)

**Comment by 3Nigma** [comment]
@pcr910303 -- We had an interesting discussion yesterday about this and, strange enough, @RaduMilici raised *the same* arguments as you did.

So, for now, we have 2 options here:
1. transpile top-level and `if` nested class definitions from `class A {}` to `A = class {}` which will allow double cell-execution to be carried out
1. get rid of the [top-level scope](https://github.com/3Nigma/nelu-kernelu/blob/master/src/session/message_loop.js#L134) we currently use to wrap the cell code in and transpile just `let` and `const`s into `var`s.  This won't solve the double `class` declaration problem though but it will allow instances to be created outside that declaration cell. To solve the double-declaration (double `class` cell-run error) we would need to transpile classes into vars as well. This will let us use `let` defined variables into other cells, but my problem here is with `const`s. Since we'll change them to `vars` as well just to be able to double run a cell, the following scenario won't throw an error (even though it should):
  -  _cell#1_: const a = 1
  - _cell#2_: a = 2

For the above to be logically consistent with the JS `const` behaviour, we would need to do extra book-keeping in the session and check each code cell for `const` mutations.

This is our current train of thought regarding this feature. We also don't like the current `var A = class {...}` workaround (nasty). 

Any input would be highly appreciated 🙇 & lets keep this ball rolling.

**Comment by goranmoomin** [comment]
@3Nigma Honestly, I’m not sure how to resolve this problem, or even if the kernel should try to resolve it.

For option 1, I don’t think that treating `class` declarations special is a good idea. Either for all declarations, or none.

For option 2, I’m not particularly offended to transpile all `let`, `const`, and all other declarations to `var` declarations (as it will be fine enough for most use cases), but IMHO:
- I’m not sure if it’s a viable option in the long term, as we can’t assume that all declarations have an expression alternative. Maybe I’m being overly picky, but one thing that comes in mind is when nodejs starts supporting ES6 modules. `import someVar, { anotherVar as someAnotherVar } from 'some-module'` doesn’t have an expression alternative... and I’m not convinced that this will be the only case. (This case might be transpiled into `require` calls but there might not be viable transpilation methods for other cases.)
- I’m also worried that this will make the kernel’s semantics depart from the official one. I’m pretty sure that extra book-keeping in the session itself will be very fragile, and there will be subtle corner cases like: what would happen if I redeclare a `const` var to a `let` var in the same cell? What if in a different cell? Etc...

IMHO, trying to work around such problem in a way that will be visible to the user is not a good workaround. I believe the cleanest way is to keep scoping variables, and print an warning message if the cell only contains declarations that won’t be exposed outside.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 3Nigma** [comment]
**You brought up some good arguments there!** 

On the other hand, since there is no standard JS definition of a (Jupyter) `cell`, I think we have both the responsibility and flexibility of defining our own way of handling **scope behaviour** when talking about this novel enclosure.
It is with this in mind that I think we should try to bridge Jupyter's mechanics (multiple `cell` execution, out of order `cell` execution, kernel interrupts, etc.) with what JS can offer. 

While transpiling `let`s into `var`s won't pose such a big problem, `const`s carry the burden of semantics which make them a bit problematic to map to `var`s. In my previous reply I raised the possibility that we could let the user execute a cell which has `const` declarations multiple times, but that we should not allow them to assign a value to such a variable later on (in effect enforcing the normal JS behaviour). As you pointed out, this might be harder to implement than it sounds.

Therefore, I would keep the current scoping behaviour of `const`s and `let`s being bounded only to the current cell, but I would transpile top level `class A { ... }` into `A = class { ... }` to make them both escape the VM code block and have them persisted across code cells allowing the user to execute the same class declaration multiple times without any other language violations. 

I'm going to PR something this weekend to try and prove a point.
